### ISSUE TITLE
HowTo

### ISSUE THREAD

**Issue by arnehaese** [janpavlis/TotalS3#1]
Hi Jan,
I am very interested in your approach for S3 plugin for total commander - but I have no idea how this would work or if it is usable, yet. 
Is it already usable? Do you have (and I probably missed it) any description how to integrate it to totalcmd?

Many thanks in advance :) 

Best wishes and greetings!

**Comment by arnehaese** [comment]
btw: I do know a bit C# and Windows dev stuff (only apprentice level I'd say though) and would be willing to collaborate, can do some good testing at least :)

**Comment by janpavlis** [comment]
Hello,
unfortunately, I managed to write only very small part of it and it's far from being usable. I started this few years ago as a hobby project since I didn't found any opensource S3 plugin for Total Commander at that time. But I didn't had time to finish it and that is unlikely to change in commings months.

IIRC the only thing which is working is the implementation of Total Commander's filesystem plugin interface, which allows it to be registered under Total Commander as a plugin so that TC displays it under virtual filesystems list (I think you just need to rename compiled `.dll` to `.wfx`/`.wfx64` to make it valid TC plugin) - everything else would have to be programmed from scratch (on the other hand, it should not be that difficult to write at least the basic functionality, S3 protocol is not a rocket science after all).

Sorry for disappointment.

Best Regards
Jan Pavlis
